name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - assigned
      - unassigned
      - review_requested
      - review_request_removed
      - ready_for_review
      - locked
      - unlocked
  workflow_dispatch:

permissions:
  security-events: write
  packages: read
  pull-requests: write
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'mountain-reverie/playwright-ci-go'
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.maintainer-changes && (contains(steps.dependabot-metadata.outputs.package-ecosystem, 'go_modules') || contains(steps.dependabot-metadata.outputs.package-ecosystem, 'github_actions')) }}
        run: gh pr merge --auto --merge "${{github.event.pull_request.html_url}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}