name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - assigned
      - unassigned
      - review_requested
      - review_request_removed
      - ready_for_review
      - locked
      - unlocked
  workflow_dispatch:

permissions:
  security-events: write
  packages: read
  pull-requests: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
